config/routes.rb
GreenBoard::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'adverts#index'
  resources :adverts, :only => [:index, :show, :new, :create, :destroy]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/advert.rb
class Advert < ActiveRecord::Base
  attr_accessible :content, :email, :phone, :icq, :skype, :name, :price, :original_ad_url, :category_id

  validates :content, :category_id, presence: true
  #validates :phone, presence: true, length: { minimum: 7, maximum: 30 },
  #				numericality: { only_integer: true }
  validates :price, length: { maximum: 12 }, allow_nil: true,
  				numericality: { only_integer: true }
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :category_id
  has_many :adverts

  has_many :subcategories, class_name: "Category", foreign_key: "category_id"
  belongs_to :parent, class_name: "Category", foreign_key: "category_id"

def ancestors
  result = []
  result << parent if parent.present?
  result
end

def title
  (ancestors + [self]).map(&:name).join(' / ')
end

def self.allcategories
collection = []
    all.each{ |x|
      x[:name] = x.parent.name + " / " + x.name if x.parent.present?
      collection << x
    }
    collection
 end
  
end

app/models/views_counter.rb
class ViewsCounter < ActiveRecord::Base
  attr_accessible :viewable_type, :viewable_id

	def self.counter(type, id)
	  counter = find_or_create_by_viewable_type_and_viewable_id(type, id)
	  counter.increment!(:views_count)
	  counter.views_count
	end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.includes(:category).order('created_at desc').all
    @vcounter = ViewsCounter.counter('Page', 'index')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adverts }
    end
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
    @advert = Advert.find(params[:id])
    @vcounter = ViewsCounter.counter('Advert', params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advert }
    end
  end

  # GET /adverts/new
  # GET /adverts/new.json
  def new
    @advert = Advert.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advert }
    end
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(params[:advert])

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render json: @advert, status: :created, location: @advert }
      else
        format.html { render action: "new" }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy

    respond_to do |format|
      format.html { redirect_to adverts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adverts/_form.html.erb
<%= form_for(@advert) do |f| %>

    <div class="container">
      <div class="row">
        <div class="span5 offset4 text error_explanation">
          <ul>
            <% @advert.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container text-center">
      <div class="span12">
          <div>
            <%= f.label :content %>
            <%= f.text_area :content %>
            <br/>
            <%= f.label :price, "Price, RUR"  %>
            <%= f.text_field :price %>
            <br/>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <br/>
            <%= f.label :phone %>
            <%= f.text_field :phone %>
            <br/>
            <%= f.label :skype %>
            <%= f.text_field :skype %>
            <br/>
            <%= f.label :email %>
            <%= f.text_field :email %>
            <br/>
            <%= f.label :icq, "ICQ" %>
            <%= f.text_field :icq %>
            <br/>
            <%= f.label :category_id, "Category" %>
            <%= f.collection_select(:category_id, Category.all, :id, :title, :include_blank => "Select category") %>
            <br/>
            <%= f.submit "Create advert", class: "btn btn-primary" %>
          </div>
      </div>
    </div>

<% end %>

app/views/adverts/index.html.erb
<h1 class="text-center">GreenBoard</h1>

  <% @adverts.each do |advert| %>

  <div class="container">
    <div class="row adv_backgr_color">

      <div class="span9">
        <div class="row">
          <div class="span6 text-left blue_text">No: <%= advert.id %></div>
          <div class="span3 text-right blue_text"><%= advert.created_at.strftime("%d/%m/%Y %H:%M") %></div>
        </div>
      <br>
      <%= advert.content %>
      <br><br>
      <% unless advert.price.nil? || advert.price == 0 %>
      <div>Price, RUR: <%= number_with_delimiter(advert.price, delimiter: " ") %></div>
      <% end %>
      <% unless advert.original_ad_url.nil? %>
      <div><%= link_to 'Original ad', advert.original_ad_url %></div>
      <% end %>
      </div>

      <div class="span3">
        <ul class="unstyled">
          <li><b>Contacts</b></li>
          <li>Name: <%= advert.name %></li>
          <li>Phone: <%= advert.phone %></li>
          <li>Skype: <%= advert.skype %></li>
          <li>Email: <%= advert.email %></li>
          <li>ICQ: <%= advert.icq %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row adv_backgr_color">
      <div class="span9">
        <div class="row">
          <div class="span6 text-left blue_text"><br><%= advert.category.title %></div>
          <div class="span3 text-right">
            <ul class="inline">
              <li class="btn"><%= link_to 'Show', advert %></li>
              <li class="btn"><%= link_to 'Destroy', advert, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
<% end %>

<div class="container text-center">
  <div class="span12">
    <div class="row">
      <div class="btn"><%= link_to 'New Advert', new_advert_path %></div>
    </div>
    <br>
    <div class="row">
      <div class="label label-success">Views: <%= @vcounter %></div>
    </div>
  </div>
</div>

app/views/adverts/new.html.erb
<h1 class="text-center">GreenBoard</h1>
<h2 class="text-center">New advert</h2>

<%= render 'form' %>

<div class="span1 offset7 btn text-center"><%= link_to 'Back', adverts_path %></div>

app/views/adverts/show.html.erb
<h1 class="text-center">GreenBoard</h1>

  <div class="container">
    <div class="row adv_backgr_color">

      <div class="span9">
        <div class="row">
          <div class="span6 text-left blue_text">No: <%= @advert.id %></div>
          <div class="span3 text-right blue_text"><%= @advert.created_at.strftime("%d/%m/%Y %H:%M") %></div>
        </div>
      <br>
      <%= @advert.content %>
      <br><br>
      <% unless @advert.price.nil? || @advert.price == 0%>
      <div>Price, RUR: <%= number_with_delimiter(@advert.price, delimiter: " ") %></div>
      <% end %>
      <% unless @advert.original_ad_url.nil? %>
      <div><%= link_to 'Original ad', @advert.original_ad_url %></div>
      <% end %>

      </div>

      <div class="span3">
        <ul class="unstyled">
          <li><b>Contacts</b></li>
          <li>Name: <%= @advert.name %></li>
          <li>Phone: <%= @advert.phone %></li>
          <li>Skype: <%= @advert.skype %></li>
          <li>Email: <%= @advert.email %></li>
          <li>ICQ: <%= @advert.icq %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row adv_backgr_color">
      <div class="span9">
        <div class="row">
          <div class="span6 text-left blue_text"><br><%= @advert.category.title %></div>
          <div class="span3 text-right">
            <ul class="inline">
              <li class="btn"><%= link_to 'Back', adverts_path %></li>
              <li class="btn"><%= link_to 'Destroy', @advert, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
<div class="span1 offset7 label label-success text-center">Views: <%= @vcounter %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenBoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>